# logging.yaml file for use with farmer_health.py v.991
# 2023-08-24

version: 1
disable_existing_loggers: False

formatters:
    console:
        format: "%(message)s"
    console_expanded:
        format: '%(module)2s:%(lineno)s - %(funcName)3s: %(levelname)3s:    %(message)s'
    standard:
        format: '%(asctime)s - %(module)2s:%(lineno)s - %(funcName)3s: %(levelname)3s %(message)s'
    error:
        format: "%(levelname)s <PID %(process)d:%(processName)s> %(module)s.%(funcName)s(): %(message)s"
    coin:
        format: '%(message)s'

handlers:
    console:
        class: logging.StreamHandler
        formatter: console_expanded
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: standard
        filename: /home/chia/farmer_health/logs/info.log
        maxBytes: 10485760 # 10MB
        backupCount: 2
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: error
        filename: /home/chia/farmer_health/logs/errors.log
        maxBytes: 10485760 # 10MB
        backupCount: 2
        encoding: utf8

    debug_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: standard
        filename: /home/chia/farmer_health/logs/debug.log
        maxBytes: 10485760
        backupCount: 2
        encoding: utf8

    critical_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: CRITICAL
        formatter: standard
        filename: /home/chia/farmer_health/logs/critical.log
        maxBytes: 10485760 # 10MB
        backupCount: 2
        encoding: utf8

    warning_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: WARNING
        formatter: standard
        filename: /home/chia/farmer_health/logs/warning.log
        maxBytes: 10485760 # 10MB
        backupCount: 2
        encoding: utf8

    farmer_health_handler:
      class: logging.handlers.RotatingFileHandler
      formatter: standard
      filename: /home/chia/farmer_health/logs/farmer_health.log
      maxBytes: 10485760 # 10MB
      backupCount: 2
      encoding: utf8

root:
    level: NOTSET
    handlers:
    propogate: no

loggers:
    __main__:
        handlers: [console, info_file_handler, error_file_handler, critical_file_handler, debug_file_handler, warning_file_handler, farmer_health_handler]
        propogate: no
